version: '3'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
        - ./www:/app
        depends_on:
        - php-fpm
        networks:
            board-project:
                ipv4_address: 10.6.0.105
    php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
        - ./www:/app
        environment:
        - "DB_PORT=3306"
        - "DB_HOST=mysql"
        depends_on:
        - mysql
        networks:
            board-project:

    php-cli:
        build:
            context: ./docker
            dockerfile: php-cli.docker
        volumes:
        - ./www:/app
        depends_on:
        - mysql

        environment:
        - "DB_PORT=3306"
        - "DB_HOST=mysql"

        command: cron -f

        tty: true

        networks:
            board-project:

    mysql:
        image: mysql:5.7
        volumes:
        - ./mysql:/var/lib/mysql
        environment:
        - "MYSQL_ROOT_PASSWORD=password"
        - "MYSQL_DATABASE=hansmedia"

        networks:
            board-project:
                ipv4_address: 10.6.0.106
    redis:
        image: redis:3.0
        networks:
            board-project:
        ports:
        - "63791:6379"

    node:
        image: node:8.6-alpine
        volumes:
        - ./:/var/www
        working_dir: /var/www
        networks:
            board-project:
        tty: true


networks:
    board-project:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.6.0.0/24